# Generated by Django 5.0 on 2025-09-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_utc', models.DateTimeField(help_text='Template anchor time in UTC')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('freq', models.CharField(choices=[('NEVER', 'Never (single event)'), ('DAILY', 'Daily'), ('WORKDAY', 'Workdays (Mon-Fri)'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly')], default='NEVER', max_length=20)),
                ('byweekday', models.JSONField(blank=True, default=list, help_text="List of weekday strings like ['MO', 'WE']. Empty = infer from start day")),
                ('interval', models.PositiveIntegerField(default=1, help_text='Interval for recurrence (2 for fortnightly)')),
                ('until_utc', models.DateTimeField(blank=True, help_text='End date for recurrence in UTC', null=True)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_utc'],
            },
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_start_utc', models.DateTimeField(help_text='Original occurrence start time in UTC (identifies which occurrence this affects)')),
                ('deleted', models.BooleanField(default=False, help_text='If True, this occurrence is deleted')),
                ('override_start_utc', models.DateTimeField(blank=True, null=True)),
                ('override_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('override_title', models.CharField(blank=True, max_length=255)),
                ('override_link', models.URLField(blank=True)),
                ('override_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendar_app.eventseries')),
            ],
            options={
                'ordering': ['occurrence_start_utc'],
                'unique_together': {('series', 'occurrence_start_utc')},
            },
        ),
    ]
