# Generated by Django 5.0 on 2025-09-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='event_type',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('1st', '1st'), ('Presentation', 'Presentation'), ('Event', 'Event')], default='Event', max_length=20),
        ),
    ]
