# Generated by Django 5.0 on 2025-09-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_eventseries_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexception',
            name='override_event_type',
            field=models.CharField(blank=True, choices=[('Meeting', 'Meeting'), ('1st', '1st'), ('Presentation', 'Presentation'), ('Event', 'Event')], max_length=20),
        ),
    ]
