# Generated by Django 5.0 on 2025-09-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_alter_eventexception_override_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexception',
            name='override_event_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
