# Generated by Django 5.0 on 2025-09-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_alter_eventexception_override_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexception',
            name='override_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='location',
            field=models.CharField(blank=True, help_text='Event location', max_length=255),
        ),
    ]
