# Generated by Django 5.0 on 2025-09-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_add_location_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexception',
            name='override_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='host',
            field=models.CharField(blank=True, help_text='Event host', max_length=255),
        ),
    ]
